### PR TITLE
Added a simple gui to download songs.

### PR DESCRIPTION
**Pull request by atulya2109**
Just paste URL using keyboard shortcuts into the field and hit download.

### CODE REVIEW

**Review by ionicc — DISMISSED** [review]
There are some indentation issues. Please fix them and commit your changes 😺

**Comment by atulya2109** [comment]
Just went through the code, couldn't find any indentation errors. The code is working perfectly fine on my computer.

**Comment by ionicc** [comment]
Alright, Could you post a screenshot of the UI

**Comment by atulya2109** [comment]
untitled

**Comment by ionicc** [comment]
The window is too big and clunky. Also, We have an option of searching for
songs as well.

**Pull request closed without merging**
